---
- name: Gather facts about NICs
  setup:
    filter: ansible_interfaces

- name: check number of NICs
  # shell: lspci | grep -i -e ethernet -e network|wc -l  #FEDORA
  shell: ls -d /sys/class/net/eth* | wc -l
  register: hw_nic_number

- name: check NIC speed  #TODO: check if working
  assert:
    that:
      - "{{ hostvars[ansible_hostname]['ansible_'~item]['speed'] }} >= {{ nic_speed_min }}"
    msg: "your card is only {{ hostvars[ansible_hostname]['ansible_'~item]['speed'] | pprint }} Mbps, but it MUST be at least {{ nic_speed_min }} Mbps"
  loop: "{{ ansible_interfaces | map('replace', '-','_') | list }}"

- name: check BONDing
  block: 
    - debug:
        msg: "check bonding"
  when: hw_nic_number > 1
  tags:
    - bonding
  

- name: check TEAMing
  block:
    - debug:
      msg: "check teaming"
  when: hw_nic_number > 1
  tags: 
    - teaming